###
POST http://185.230.163.241:8000/signup/ HTTP/1.1
content-type: application/json

{
    "username":"user2",
    "password":"pass1"
}

###
POST http://185.230.163.241:8000/login/ HTTP/1.1
content-type: application/json

{
    "username":"user2",
    "password":"pass1"
}

###
GET http://185.230.163.241:8000/test_token/ HTTP/1.1
# content-type: application/json
Authorization: Token ae9ee58f0fe3e2dfccf67a4cd2cb892320110c13

###
GET http://185.230.163.241:8000/devices/ HTTP/1.1
# content-type: application/json
Authorization: Token ae9ee58f0fe3e2dfccf67a4cd2cb892320110c13

###
PUT http://185.230.163.241:8000/devices/ HTTP/1.1
content-type: application/json
Authorization: Token ae9ee58f0fe3e2dfccf67a4cd2cb892320110c13

{"uid" : "d3", "version":"1"}

###
DELETE  http://185.230.163.241:8000/devices/ HTTP/1.1
content-type: application/json
Authorization: Token ae9ee58f0fe3e2dfccf67a4cd2cb892320110c13

{"uid" : "d2", "version":"1"}


### /api/version/uid/...
GET http://185.230.163.241:8000/api/1/d3/sensors/ HTTP/1.1
# content-type: application/json
Authorization: Token ae9ee58f0fe3e2dfccf67a4cd2cb892320110c13

###
POST http://185.230.163.241:8000/api/1/d3/sensors/ HTTP/1.1
content-type: application/json
Authorization: Token ae9ee58f0fe3e2dfccf67a4cd2cb892320110c13

{"time":"1zzz", "temp": 18, "humid": 1.25, "lpg": 13, "smk": 23}

###
GET http://185.230.163.241:8000/api/1/d3/relays/ HTTP/1.1
# content-type: application/json
Authorization: Token ae9ee58f0fe3e2dfccf67a4cd2cb892320110c13

###
POST http://185.230.163.241:8000/api/1/d3/relays/ HTTP/1.1
content-type: application/json
Authorization: Token ae9ee58f0fe3e2dfccf67a4cd2cb892320110c13

{"rel1": false, "rel2": true, "rel3": true, "rel4": false}





###
# GET http://185.230.163.241:8000/api/kgthj4a56etj1tujaetj54at1eahu5e4aj5/sensors/ HTTP/1.1
# content-type: application/json


# GET http://185.230.163.241:8000/api/kgthj4a56etj1tujaetj54at1eahu5e4aj5/relays/ HTTP/1.1
###
# POST http://185.230.163.241:8000/api/kgthj4a56etj1tujaetj54at1eahu5e4aj5/sensors/ HTTP/1.1
# content-type: application/json

# {"time":"1", "temp": 441, "humid": 1.256562, "lpg": 13, "smok": 23}