# Generated by Django 4.2 on 2023-08-03 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='', max_length=100)),
                ('token', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, default='', max_length=50)),
                ('temp', models.FloatField(default=0.0, null=True)),
                ('humid', models.FloatField(default=0.0, null=True)),
                ('lpg', models.FloatField(default=0.0, null=True)),
                ('smok', models.FloatField(default=0.0, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='app1.device')),
            ],
        ),
        migrations.CreateModel(
            name='Relays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay1', models.CharField(blank=True, default='', max_length=50)),
                ('relay2', models.CharField(blank=True, default='', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relays', to='app1.device')),
            ],
        ),
    ]
