# Generated by Django 4.2 on 2023-08-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relays',
            name='relay1',
        ),
        migrations.RemoveField(
            model_name='relays',
            name='relay2',
        ),
        migrations.AddField(
            model_name='relays',
            name='rel1',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='relays',
            name='rel2',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='relays',
            name='rel3',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='relays',
            name='rel4',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
