# Generated by Django 4.2 on 2023-08-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_relays_relay1_remove_relays_relay2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensors',
            old_name='smok',
            new_name='smk',
        ),
    ]
