# Generated by Django 4.2 on 2023-08-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='version',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
